
-- Minority standalone / Quick Games server-authoritative state.
-- The game contract remains docs/games/minority/GAME_CONTRACT.md.

alter table public.quick_game_lobbies
  drop constraint if exists quick_game_lobbies_game_key_check;
alter table public.quick_game_lobbies
  add constraint quick_game_lobbies_game_key_check
  check (game_key in ('dna','minority'));

create table if not exists private.minority_questions (
  question_id bigint generated by default as identity primary key,
  option_count smallint not null check (option_count between 2 and 4),
  options jsonb not null check (jsonb_typeof(options)='array' and jsonb_array_length(options)=option_count),
  is_active boolean not null default true,
  unique(options)
);
alter table private.minority_questions enable row level security;
revoke all on private.minority_questions from public, anon, authenticated;

insert into private.minority_questions(option_count,options)
select 2, value
from jsonb_array_elements(
'[
["Rechts","Links"],["Oben","Unten"],["Heiß","Kalt"],["Drinnen","Draußen"],["Regen","Sonne"],
["Tag","Nacht"],["Früh","Spät"],["Cola","Fanta"],["Mayo","Ketchup"],["Nudeln","Reis"],
["Apfel","Banane"],["Schokolade","Chips"],["Dusche","Badewanne"],["Fenster","Tür"],["Treppe","Aufzug"],
["Fliegen","Fahren"],["Hotel","Ferienwohnung"],["Strand","Pool"],["Camping","Hotel"],["Film","Serie"],
["Kino","Zuhause"],["Musik","Podcast"],["Spotify","YouTube"],["Buch","Film"],["Horror","Comedy"],
["Action","Drama"],["Marvel","DC"],["Harry Potter","Herr der Ringe"],["Star Wars","Star Trek"],["Mario","Sonic"],
["FIFA","Call of Duty"],["Maus","Controller"],["Chrome","Safari"],["Anrufen","Schreiben"],["Foto","Video"],
["Selfie","Gruppenfoto"],["Frühaufsteher","Nachteule"],["Planen","Spontan"],["Chaos","Ordnung"],["Laut","Leise"],
["Schnell","Langsam"],["Kopf","Bauch"],["Glück","Können"],["Risiko","Sicherheit"],["Geld","Freizeit"],
["Bekannt","Unbekannt"],["Vergangenheit","Zukunft"],["Fragen","Antworten"],["Gewinnen","Spaß"],["Allein","Gruppe"],
["Gastgeber","Gast"],["Wahrheit","Pflicht"],["Reden","Zuhören"],["Tanzen","Singen"],["Kochen","Bestellen"],
["Sport","Gaming"],["Tischtennis","Dart"],["Fitnessstudio","Laufen"],["Angreifen","Verteidigen"],["Kraft","Geschwindigkeit"],
["Linksfuß","Rechtsfuß"],["Schwarz","Weiß"],["Kreis","Quadrat"],["Groß","Klein"],["Rund","Eckig"],
["Voll","Leer"],["Hell","Dunkel"],["Hoch","Tief"],["Vorne","Hinten"],["Innen","Außen"],
["Gerade","Kurve"],["Kopf","Zahl"],["Eins","Zwei"],["Plus","Minus"],["Ja","Nein"],
["Jetzt","Später"],["Mehr","Weniger"],["Anfang","Ende"],["Alt","Neu"]
]'::jsonb) value
on conflict(options) do nothing;

insert into private.minority_questions(option_count,options)
select 3, value
from jsonb_array_elements(
'[
["Frühstück","Mittagessen","Abendessen"],["Schule","Uni","Arbeit"],["Dusche","Sauna","Whirlpool"],
["Balkon","Terrasse","Garten"],["Hemd","Hoodie","T-Shirt"],["Sneakers","Stiefel","Sandalen"],
["Gold","Silber","Bronze"],["Rock","Pop","Hip-Hop"],["WhatsApp","Telegram","Snapchat"],
["Comedy","Thriller","Dokumentation"],["Frühstücksei","Müsli","Toast"],["Gabel","Messer","Löffel"],
["Taxi","E-Scooter","Motorrad"],["Keller","Erdgeschoss","Dachgeschoss"],["Kissen","Decke","Matratze"],
["Augen","Ohren","Nase"],["Morgen","Mittag","Abend"],["Zuhause","Büro","Café"],["Tick","Trick","Track"]
]'::jsonb) value
on conflict(options) do nothing;

insert into private.minority_questions(option_count,options)
select 4, value
from jsonb_array_elements(
'[
["Frühling","Sommer","Herbst","Winter"],["Nord","Süd","Ost","West"],["Rot","Blau","Grün","Gelb"],
["Montag","Mittwoch","Freitag","Sonntag"],["Pizza","Burger","Döner","Pasta"],["Hund","Katze","Pferd","Vogel"],
["PC","PlayStation","Xbox","Switch"],["Auto","Fahrrad","Bahn","Zu Fuß"],["Netflix","YouTube","TikTok","Instagram"],
["Meer","Berge","Stadt","Land"],["Süß","Salzig","Sauer","Scharf"],["Fußball","Basketball","Tennis","Tischtennis"],
["Herz","Pik","Karo","Kreuz"],["Feuer","Wasser","Erde","Luft"],["Januar","April","Juli","Oktober"]
]'::jsonb) value
on conflict(options) do nothing;

create table if not exists private.quick_minority_games (
  lobby_id uuid primary key references public.quick_game_lobbies(lobby_id) on delete cascade,
  difficulty text not null check (difficulty in ('EASY','NORMAL','HARDCORE')),
  round_count smallint not null check (round_count in (5,10,15)),
  round_no smallint not null default 1 check (round_no between 1 and 15),
  round_value integer not null default 1 check (round_value>=1),
  stage text not null default 'READY' check (stage in ('READY','PLAYING','RESOLVED','FINISHED')),
  question_id bigint references private.minority_questions(question_id),
  question_options jsonb not null default '[]'::jsonb,
  scores jsonb not null default '[0,0,0,0]'::jsonb,
  reveal jsonb,
  revision bigint not null default 1,
  updated_at timestamptz not null default now()
);
alter table private.quick_minority_games enable row level security;
revoke all on private.quick_minority_games from public, anon, authenticated;

create table if not exists private.quick_minority_ready (
  lobby_id uuid not null references public.quick_game_lobbies(lobby_id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  ready_at timestamptz not null default now(),
  primary key(lobby_id,user_id)
);
alter table private.quick_minority_ready enable row level security;
revoke all on private.quick_minority_ready from public, anon, authenticated;

create table if not exists private.quick_minority_choices (
  lobby_id uuid not null references public.quick_game_lobbies(lobby_id) on delete cascade,
  round_no smallint not null,
  seat smallint not null check (seat between 1 and 4),
  choice smallint not null check (choice between 1 and 4),
  user_id uuid references auth.users(id) on delete cascade,
  is_bot boolean not null default false,
  submitted_at timestamptz not null default now(),
  primary key(lobby_id,round_no,seat)
);
alter table private.quick_minority_choices enable row level security;
revoke all on private.quick_minority_choices from public, anon, authenticated;

create or replace function private.quick_minority_option_count(p_lobby_id uuid,p_difficulty text,p_round_no smallint)
returns smallint
language sql immutable
set search_path=pg_catalog
as $$
  select case
    when p_round_no % 5 <> 0 or p_difficulty='EASY' then 2
    when p_difficulty='NORMAL' then 3
    when get_byte(decode(md5(p_lobby_id::text||':'||p_round_no::text),'hex'),0) % 2 = 0 then 3
    else 4 end::smallint;
$$;
revoke all on function private.quick_minority_option_count(uuid,text,smallint) from public,anon,authenticated;

create or replace function private.quick_minority_pick_question(
  p_lobby_id uuid,p_difficulty text,p_round_no smallint
) returns table(question_id bigint,options jsonb)
language sql stable
set search_path=pg_catalog,private
as $$
  select q.question_id,q.options
  from private.minority_questions q
  where q.is_active
    and q.option_count=private.quick_minority_option_count(p_lobby_id,p_difficulty,p_round_no)
    and not exists(
      select 1 from private.quick_minority_games g
      where g.lobby_id=p_lobby_id and g.question_id=q.question_id and g.round_no<>p_round_no
    )
  order by md5(p_lobby_id::text||':'||p_round_no::text||':'||q.question_id::text)
  limit 1;
$$;
revoke all on function private.quick_minority_pick_question(uuid,text,smallint) from public,anon,authenticated;

create or replace function private.quick_minority_virtual_players(p_lobby_id uuid,p_uid uuid)
returns jsonb
language sql stable security definer
set search_path=pg_catalog,public
as $$
with seats as (select generate_series(1,4)::smallint seat),
humans as (
  select p.seat,p.user_id,p.display_name
  from public.quick_game_lobby_players p where p.lobby_id=p_lobby_id and p.seat between 1 and 4
)
select jsonb_agg(jsonb_build_object(
  'seat',s.seat,
  'user_id',h.user_id,
  'display_name',coalesce(h.display_name,'BOT '||s.seat::text),
  'is_me',h.user_id=p_uid,
  'is_bot',h.user_id is null,
  'ready',case when h.user_id is null then true else exists(
    select 1 from private.quick_minority_ready r where r.lobby_id=p_lobby_id and r.user_id=h.user_id
  ) end
) order by s.seat)
from seats s left join humans h using(seat);
$$;
revoke all on function private.quick_minority_virtual_players(uuid,uuid) from public,anon,authenticated;

create or replace function private.quick_minority_resolve_if_ready(p_lobby_id uuid)
returns void
language plpgsql security definer
set search_path=pg_catalog,public,private
as $$
declare
  g private.quick_minority_games%rowtype;
  human_count int; submitted_humans int; option_count int;
  s int; chosen int; counts int[]:=array[0,0,0,0]; min_count int; max_count int;
  winners int[]:=array[]::int[]; penalties int[]:=array[]::int[];
  score_arr int[]:=array[0,0,0,0]; seat_choice int[]:=array[0,0,0,0];
  award int; leader int; has_minority boolean:=false; four_zero boolean:=false;
  winning_options int[]:=array[]::int[];
begin
  select * into g from private.quick_minority_games where lobby_id=p_lobby_id for update;
  if not found or g.stage<>'PLAYING' then return; end if;
  option_count:=jsonb_array_length(g.question_options);

  select count(*) into human_count from public.quick_game_lobby_players where lobby_id=p_lobby_id and seat between 1 and 4;
  select count(*) into submitted_humans from private.quick_minority_choices c
    where c.lobby_id=p_lobby_id and c.round_no=g.round_no and not c.is_bot;
  if submitted_humans<human_count then return; end if;

  for s in 1..4 loop
    if not exists(select 1 from private.quick_minority_choices c where c.lobby_id=p_lobby_id and c.round_no=g.round_no and c.seat=s) then
      chosen:=1+floor(random()*option_count)::int;
      insert into private.quick_minority_choices(lobby_id,round_no,seat,choice,is_bot)
      values(p_lobby_id,g.round_no,s,chosen,true);
    end if;
  end loop;

  for s in 1..4 loop
    select c.choice into chosen from private.quick_minority_choices c
      where c.lobby_id=p_lobby_id and c.round_no=g.round_no and c.seat=s;
    seat_choice[s]:=chosen;
    counts[chosen]:=counts[chosen]+1;
    score_arr[s]:=coalesce((g.scores->>(s-1))::int,0);
  end loop;

  select min(x),max(x) into min_count,max_count from unnest(counts[1:option_count]) x where x>0;
  has_minority:=coalesce(min_count<max_count,false);
  if has_minority then
    award:=case when g.difficulty='EASY' then 1 else g.round_value end;
    for s in 1..4 loop
      if counts[seat_choice[s]]=min_count then
        winners:=array_append(winners,s);
        if not (seat_choice[s]=any(winning_options)) then winning_options:=array_append(winning_options,seat_choice[s]); end if;
        score_arr[s]:=score_arr[s]+award;
      end if;
    end loop;
  else
    award:=0;
  end if;

  four_zero:=4=any(counts[1:option_count]);
  if not has_minority and g.difficulty='HARDCORE' and four_zero then
    select max(x) into leader from unnest(score_arr) x;
    for s in 1..4 loop
      if score_arr[s]=leader then
        penalties:=array_append(penalties,s);
        score_arr[s]:=score_arr[s]-1;
      end if;
    end loop;
  end if;

  update private.quick_minority_games set
    scores=to_jsonb(score_arr),
    stage='RESOLVED',
    reveal=jsonb_build_object(
      'counts',to_jsonb(counts[1:option_count]),
      'hasMinority',has_minority,
      'winningSeats',to_jsonb(winners),
      'penaltySeats',to_jsonb(penalties),
      'winningOptions',to_jsonb(winning_options),
      'award',award,
      'nextRoundValue',case when g.difficulty<>'EASY' and not has_minority then g.round_value+1 else 1 end,
      'isFourZero',four_zero
    ),
    revision=revision+1,updated_at=now()
  where lobby_id=p_lobby_id;
end;
$$;
revoke all on function private.quick_minority_resolve_if_ready(uuid) from public,anon,authenticated;

create or replace function public.get_quick_minority_game(p_lobby_id uuid)
returns jsonb
language plpgsql security definer
set search_path=pg_catalog,public,private
as $$
declare
  uid uuid:=auth.uid(); g private.quick_minority_games%rowtype; my_seat smallint; my_choice smallint;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  if not private.is_quick_game_lobby_member(p_lobby_id,uid) then raise exception 'LOBBY_FORBIDDEN'; end if;
  select * into g from private.quick_minority_games where lobby_id=p_lobby_id;
  if not found then raise exception 'NOT_CONFIGURED'; end if;
  select p.seat into my_seat from public.quick_game_lobby_players p where p.lobby_id=p_lobby_id and p.user_id=uid;
  select c.choice into my_choice from private.quick_minority_choices c
    where c.lobby_id=p_lobby_id and c.round_no=g.round_no and c.seat=my_seat;
  return jsonb_build_object(
    'stage',g.stage,'difficulty',g.difficulty,'roundCount',g.round_count,'round',g.round_no,
    'roundValue',g.round_value,'scores',g.scores,'players',private.quick_minority_virtual_players(p_lobby_id,uid),
    'question',jsonb_build_object('id',g.question_id,'options',g.question_options,'optionCount',jsonb_array_length(g.question_options),'chaos',jsonb_array_length(g.question_options)>2),
    'myChoice',my_choice,'reveal',case when g.stage in ('RESOLVED','FINISHED') then g.reveal else null end,
    'revision',g.revision
  );
end;
$$;

create or replace function public.configure_quick_minority_game(
  p_lobby_id uuid,p_difficulty text,p_round_count smallint
) returns jsonb
language plpgsql security definer
set search_path=pg_catalog,public,private
as $$
declare
  uid uuid:=auth.uid(); diff text:=upper(coalesce(p_difficulty,'')); qid bigint; opts jsonb;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  if diff not in ('EASY','NORMAL','HARDCORE') then raise exception 'INVALID_DIFFICULTY'; end if;
  if p_round_count not in (5,10,15) then raise exception 'INVALID_ROUND_COUNT'; end if;
  perform 1 from public.quick_game_lobbies l
    where l.lobby_id=p_lobby_id and l.host_user_id=uid and l.game_key='minority' and l.status='LIVE'
    for update;
  if not found then raise exception 'HOST_LIVE_LOBBY_REQUIRED'; end if;

  select * into qid,opts from private.quick_minority_pick_question(p_lobby_id,diff,1);
  delete from private.quick_minority_choices where lobby_id=p_lobby_id;
  delete from private.quick_minority_ready where lobby_id=p_lobby_id;
  insert into private.quick_minority_games(lobby_id,difficulty,round_count,round_no,round_value,stage,question_id,question_options,scores,reveal,revision)
  values(p_lobby_id,diff,p_round_count,1,1,'READY',qid,opts,'[0,0,0,0]'::jsonb,null,1)
  on conflict(lobby_id) do update set difficulty=excluded.difficulty,round_count=excluded.round_count,
    round_no=1,round_value=1,stage='READY',question_id=excluded.question_id,question_options=excluded.question_options,
    scores='[0,0,0,0]'::jsonb,reveal=null,revision=private.quick_minority_games.revision+1,updated_at=now();
  update public.quick_game_lobbies set setup_status='READY',
    setup_json=jsonb_build_object('difficulty',diff,'roundCount',p_round_count),updated_at=now()
    where lobby_id=p_lobby_id;
  return public.get_quick_minority_game(p_lobby_id);
end;
$$;

create or replace function public.ready_quick_minority_game(p_lobby_id uuid)
returns jsonb
language plpgsql security definer
set search_path=pg_catalog,public,private
as $$
declare uid uuid:=auth.uid(); human_count int; ready_count int;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  if not private.is_quick_game_lobby_member(p_lobby_id,uid) then raise exception 'LOBBY_FORBIDDEN'; end if;
  perform 1 from private.quick_minority_games where lobby_id=p_lobby_id and stage in ('READY','PLAYING') for update;
  if not found then raise exception 'READY_STAGE_REQUIRED'; end if;
  insert into private.quick_minority_ready(lobby_id,user_id) values(p_lobby_id,uid) on conflict do nothing;
  select count(*) into human_count from public.quick_game_lobby_players where lobby_id=p_lobby_id and seat between 1 and 4;
  select count(*) into ready_count from private.quick_minority_ready where lobby_id=p_lobby_id;
  if ready_count>=human_count then
    update private.quick_minority_games set stage='PLAYING',revision=revision+1,updated_at=now()
    where lobby_id=p_lobby_id and stage='READY';
  end if;
  return public.get_quick_minority_game(p_lobby_id);
end;
$$;

create or replace function public.submit_quick_minority_choice(p_lobby_id uuid,p_choice smallint)
returns jsonb
language plpgsql security definer
set search_path=pg_catalog,public,private
as $$
declare uid uuid:=auth.uid(); g private.quick_minority_games%rowtype; seat_no smallint; option_count int;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into g from private.quick_minority_games where lobby_id=p_lobby_id for update;
  if not found or g.stage<>'PLAYING' then raise exception 'PLAYING_STAGE_REQUIRED'; end if;
  select p.seat into seat_no from public.quick_game_lobby_players p where p.lobby_id=p_lobby_id and p.user_id=uid and p.seat between 1 and 4;
  if seat_no is null then raise exception 'LOBBY_FORBIDDEN'; end if;
  option_count:=jsonb_array_length(g.question_options);
  if p_choice<1 or p_choice>option_count then raise exception 'INVALID_CHOICE'; end if;
  insert into private.quick_minority_choices(lobby_id,round_no,seat,choice,user_id,is_bot)
  values(p_lobby_id,g.round_no,seat_no,p_choice,uid,false)
  on conflict(lobby_id,round_no,seat) do nothing;
  if not found then raise exception 'ALREADY_SUBMITTED'; end if;
  perform private.quick_minority_resolve_if_ready(p_lobby_id);
  return public.get_quick_minority_game(p_lobby_id);
end;
$$;

create or replace function public.advance_quick_minority_game(p_lobby_id uuid)
returns jsonb
language plpgsql security definer
set search_path=pg_catalog,public,private
as $$
declare uid uuid:=auth.uid(); g private.quick_minority_games%rowtype; qid bigint; opts jsonb; next_value int;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  if not private.is_quick_game_lobby_member(p_lobby_id,uid) then raise exception 'LOBBY_FORBIDDEN'; end if;
  select * into g from private.quick_minority_games where lobby_id=p_lobby_id for update;
  if not found or g.stage<>'RESOLVED' then raise exception 'RESOLVED_STAGE_REQUIRED'; end if;
  if g.round_no>=g.round_count then
    update private.quick_minority_games set stage='FINISHED',revision=revision+1,updated_at=now()
    where lobby_id=p_lobby_id;
    return public.get_quick_minority_game(p_lobby_id);
  end if;
  next_value:=coalesce((g.reveal->>'nextRoundValue')::int,1);
  select * into qid,opts from private.quick_minority_pick_question(p_lobby_id,g.difficulty,g.round_no+1);
  update private.quick_minority_games set round_no=g.round_no+1,round_value=next_value,stage='PLAYING',
    question_id=qid,question_options=opts,reveal=null,revision=revision+1,updated_at=now()
  where lobby_id=p_lobby_id;
  return public.get_quick_minority_game(p_lobby_id);
end;
$$;

revoke all on function public.get_quick_minority_game(uuid) from public;
revoke all on function public.configure_quick_minority_game(uuid,text,smallint) from public;
revoke all on function public.ready_quick_minority_game(uuid) from public;
revoke all on function public.submit_quick_minority_choice(uuid,smallint) from public;
revoke all on function public.advance_quick_minority_game(uuid) from public;
grant execute on function public.get_quick_minority_game(uuid) to authenticated;
grant execute on function public.configure_quick_minority_game(uuid,text,smallint) to authenticated;
grant execute on function public.ready_quick_minority_game(uuid) to authenticated;
grant execute on function public.submit_quick_minority_choice(uuid,smallint) to authenticated;
grant execute on function public.advance_quick_minority_game(uuid) to authenticated;

create or replace function public.create_quick_game_lobby(p_game_key text default 'dna')
returns jsonb
language plpgsql security definer
set search_path=pg_catalog,public,private
as $$
declare uid uuid:=auth.uid(); gid text:=lower(coalesce(p_game_key,'')); lid uuid; code text; tries int:=0; max_players smallint;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  if gid not in ('dna','minority') then raise exception 'GAME_NOT_AVAILABLE'; end if;
  max_players:=case when gid='minority' then 4 else 8 end;
  loop
    tries:=tries+1; code:='QG-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6));
    begin
      insert into public.quick_game_lobbies(join_code,game_key,host_user_id,max_human_players)
      values(code,gid,uid,max_players) returning lobby_id into lid;
      exit;
    exception when unique_violation then if tries>=5 then raise; end if; end;
  end loop;
  insert into public.quick_game_lobby_players(lobby_id,user_id,seat,display_name)
  values(lid,uid,1,coalesce(private.quick_game_display_name(uid),'PLAYER'));
  return public.get_quick_game_lobby(lid);
end;
$$;

create or replace function public.get_quick_game_lobby(p_lobby_id uuid)
returns jsonb
language plpgsql security definer
set search_path=pg_catalog,public,private
as $$
declare uid uuid:=auth.uid(); l public.quick_game_lobbies%rowtype;
begin
  if uid is null then raise exception 'AUTH_REQUIRED'; end if;
  if not private.is_quick_game_lobby_member(p_lobby_id,uid) then raise exception 'LOBBY_FORBIDDEN'; end if;
  select * into l from public.quick_game_lobbies where lobby_id=p_lobby_id;
  update public.quick_game_lobby_players set last_seen_at=now() where lobby_id=p_lobby_id and user_id=uid;
  return jsonb_build_object(
    'lobby_id',l.lobby_id,'join_code',l.join_code,'game_key',l.game_key,'status',l.status,
    'is_host',l.host_user_id=uid,'bots_filled',l.bots_filled,'max_human_players',l.max_human_players,
    'setup_status',l.setup_status,'setup',l.setup_json,
    'players',coalesce((select jsonb_agg(jsonb_build_object(
      'user_id',p.user_id,'display_name',p.display_name,'seat',p.seat,'is_me',p.user_id=uid,'score',r.score
    ) order by p.seat) from public.quick_game_lobby_players p
      left join public.quick_game_results r on r.lobby_id=p.lobby_id and r.user_id=p.user_id
      where p.lobby_id=p_lobby_id),'[]'::jsonb),
    'bot_scores',l.bot_scores,'result_count',(select count(*) from public.quick_game_results r where r.lobby_id=p_lobby_id),
    'launch_path',case when l.status='LIVE' and l.game_key='dna' then '/dna-test/?quick_lobby='||l.lobby_id::text
                       when l.status='LIVE' and l.game_key='minority' then '/minority-test/?quick_lobby='||l.lobby_id::text
                       else null end
  );
end;
$$;

revoke all on function public.create_quick_game_lobby(text) from public;
revoke all on function public.get_quick_game_lobby(uuid) from public;
grant execute on function public.create_quick_game_lobby(text) to authenticated;
grant execute on function public.get_quick_game_lobby(uuid) to authenticated;
